#! /bin/sh
# Author:  Julian R Yon <julian@julianyon.net>
# Date:    2015-04-24
# Licence: Public domain (CC0)
#          http://creativecommons.org/publicdomain/zero/1.0/
#          To the extent possible under law, the author has waived all
#          copyright and related or neighboring rights to this work.
#          Acknowledgement is appreciated, but not required.

findmnt -nurR -d backward \
| grep '^/lib/modules' | cut -d' ' -f1 \
| xargs umount
